# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sem_extractor}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["apneadiving"]
  s.date = %q{2010-10-02}
  s.description = %q{Extracts data from semantics APIs: zemanta, textwise, opencalais and yahoo}
  s.email = %q{apnea.diving.deep@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/.DS_Store",
     "lib/apis/calais.rb",
     "lib/apis/textwise.rb",
     "lib/apis/yahoo.rb",
     "lib/apis/zemanta.rb",
     "lib/sem_extractor.rb",
     "pkg/sem_extractor-0.0.0.gem",
     "pkg/sem_extractor-0.0.1.gem",
     "pkg/sem_extractor-0.0.2.gem",
     "sem_extractor.gemspec",
     "test/helper.rb",
     "test/test_sem_extractor.rb"
  ]
  s.homepage = %q{http://github.com/apneadiving/sem_extractor}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Extracts data from semantics APIs: zemanta, textwise, opencalais and yahoo}
  s.test_files = [
    "test/helper.rb",
     "test/test_sem_extractor.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

